[target.x86_64-unknown-linux-gnu]
image = 'yossy4411/rust-cross-seismodl:linux-x86_64-latest'

[target.aaarch64-unknown-linux-gnu]
image = 'yossy4411/rust-cross-seismodl:linux-aarch64-latest'

[target.aarch64-unknown-linux-musl]
image = 'yossy4411/rust-cross-seismodl:linux-aarch64-musl-latest'