name: Build

on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-20.04  # ARM64をサポートするUbuntu環境を選択

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Add ARM64 target
        run: rustup target add aarch64-unknown-linux-gnu  # ARM64ターゲットを追加

      - name: Install cross-compilation dependencies
        run: sudo apt-get install -y gcc-aarch64-linux-gnu libssl-dev

      - name: Build for ARM64
        run: cargo build --target aarch64-unknown-linux-gnu  # ARM64用にビルド

      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: arm64-build
          path: target/aarch64-unknown-linux-gnu/debug/seismometer-downloader  # ビルド成果物をアップロード